### ISSUE TITLE
Changing PIN makes the software crash.

### ISSUE THREAD

**Issue by Jens70** [oyzzo/MemTypeTool#24] opened 2017-06-05 07:43 UTC
Changing the PIN from 0000 to something else makes the software crash. If restarting the program and then trying the new PIN does not work, but the old 0000 works. When reading and 100% is reached the software crashes again.

If setting the PIN again in the same way as above, it crashes again, but this time it starts writing before crashing, and if then starting the software again it is possible to use the software with the new PIN and the database is readable again.

**Comment by oyzzo** [comment] 2017-06-05 12:57
Hi @Jens70 !

wow, that problem I have never experienced. I'll try to replicate it this afternoon. 

Can you paste the crash log? I suspect it's a library related issue and could also be the reason of the other issues that you're experiencing. 

In what OS version did it happen? Linux Mint 18.1 64 bits?, I'll prepare a virtual machine to reproduce it and find the cause.

**Comment by Jens70** [comment] 2017-06-05 16:08
Hi oyzzo!

Yes it is my 18.1 Mint on 64bit. I am unable to reproduce the error. I have tried many things and I have used both of my sticks. I changed the pin back to 0000 and then my real PIN and back, but without the software crashing. The stick that I used when I got the crash was the same one that kept crashing before I entered a keyboard layout. I don't know if that has something to do with it. The PIN on that stick had never been had its PIN changed either. The other stick had been in use on the Python version, so I suspect that it might have something to do with first use of a stick. However I am very pleased to see everything working now and despite all my previous problem, I think this stick is probably the coolest and most useful hardware I ever have bought. If the issue comes back I will post the complete output next time.

**Comment by oyzzo** [comment] 2017-06-05 18:56
Hi @Jens70 !

Great to hear that everything is working now!
I'm also happy that you shared your issues with us so we can keep improving everything. 

So I close the issues and if they appear again we'll re-open them.

Anyway I'll keep an eye on the "First use" theory, as it may point to something. It makes sense as the dongles we use for testing are always the same, and not in a "First use" state.

Thanks!

**Closed as completed by oyzzo** 2017-06-05 18:56 UTC
