### ISSUE TITLE
[C++ Version] Clear PIN after every transaction.

### ISSUE THREAD

**Issue by primetoxinz** [oyzzo/MemTypeTool#18] opened 2017-05-12 19:03 UTC
I compiled the C++ version of this and have been testing it out for my new memtype (just got it today :) ) and have noticed that when entering a PIN into the textbox it stays there as long as the window is open. This seems quite risk to just leave it and could lend the risk of someone click the show button and finding your pin. 

I think it would be best to clear the textbox every time an action which requires is done, reads, writes, exports, etc

**Comment by oyzzo** [comment] 2017-05-15 16:15
Hi @primetoxinz,

Thank you very much for your feedback!

I totally agree with you, having the PIN always there can be a risk in some cases.

I'll make it ask for the PIN when it's needed like the old version did :)

Regards,
Noel

**Comment by oyzzo** [comment] 2017-05-16 16:28
Hi @primetoxinz again :)

I've added a "remember PIN" toggle button, next to the PIN. 

Commit c7e2b8f.

By default the PIN is cleared every time as you suggested but, if you check the "remember PIN" button, then it's kept.

We'll try this and see if it's a good solution.

Thanks again for your help!

Regards,
Noel

**Comment by primetoxinz** [comment] 2017-05-16 16:34
I pulled and attempted to read my Memtype and I got [this crash](https://gist.github.com/primetoxinz/bbe47f82bfd087f10ff288190e3923c9)

**Comment by oyzzo** [comment] 2017-05-16 16:43
Woow, that's an ugly crash.

Can you pull again to verify that you're up to date with the server?
Did you do a clean and then a build again?

Can you describe the steps you did so I can try to reproduce it?

Thanks!

**Comment by primetoxinz** [comment] 2017-05-16 16:50
Completely re-cloned to project to double check it wasn't that.

Steps to reproduce:
1. Cloned the `rewrite` branch
2. Opened `MemTypeManager.pro` with Qt Creator
3. Build -> Run 
4. Plug in a Memtype, unlock it manually.
5. Enter the PIN into the textbox
6. Click Read.
7. Read process progresses to 100%
8. Immediately segfaults when the Read window closes.

**Comment by primetoxinz** [comment] 2017-05-16 16:55
This appears to be happening on my previous compile on `1b992f`, which it did not before, lending me to believe it is a system library causing the issue.

**Comment by oyzzo** [comment] 2017-05-16 17:01
I may upload buggy code sometimes to this branch, I did a double checking :)

I repeated all your steps and couldn't reproduce it.

Is it still happening?
If so, could you place a breakpoint in qt-creator and run with debugger stepping until it crashes?

**Comment by primetoxinz** [comment] 2017-05-16 17:27
I may be reading this incorrectly as I don't normally write cpp, but it appears that it is segfaulting at [one of these lines](https://github.com/oyzzo/MemTypeTool/blob/rewrite/MemTypeManager/mainwindow.cpp#L400-L401). I don't quite understand, but it sometimes makes it to the second one, sometimes doesn't.

**Comment by oyzzo** [comment] 2017-05-16 17:39
Can't see any reason for it to segfault...

I've added some PIN Hash checking into this method, can you pull the code from the branch and rebuild?

Let me know if it still happens.

**Comment by primetoxinz** [comment] 2017-05-16 17:46
Nope, no change :(

**Comment by primetoxinz** [comment] 2017-05-16 17:49
Just a long shot, could it have something to do with a system upgrade updating `qt5ct (0.31-1 -> 0.32-1)`?
guess not, downgraded back to 0.31-1, still neither previous compile nor new work.

**Comment by oyzzo** [comment] 2017-05-16 18:00
I see you use Linux too, can you send me the binary called "MemTypeManager" under the folder "build-MemTypeManager-Desktop_Qt_5_8_0_GCC_64bit-Debug" (or similar) generated by Qt-Creator.

I'll run it on my computer with the debugger, let's see if I can see something :)

**Comment by primetoxinz** [comment] 2017-05-16 18:04
Yeah, currently running Arch Linux 4.10.13-1
Link to the binary: https://www.dropbox.com/s/8qog0b1on4a2bre/MemTypeManager?dl=0

**Comment by oyzzo** [comment] 2017-05-16 18:25
Can't run it, too many different versions of libraries :(

Can you try to remove the whole project, including the git dir, then clone again, open in qt-creator and build?

It also could be related with the credentials too.
Can you write only 1 Credential to the device, and then try to read it back?

**Comment by primetoxinz** [comment] 2017-05-16 18:32
Ok. I used the Python version to clear all but a single credential, then completely recloned the project and it worked on read.

**Comment by primetoxinz** [comment] 2017-05-16 18:35
As soon as I reimported my credentials it crashes again, so I'll try to track down which one is causing the problem.

**Comment by oyzzo** [comment] 2017-05-16 18:43
Ok, it maybe was something wrong with the information written in the device.
I'll test it deeply before I release it.

Also I was doing some incorrect character manipulation (it was half implemented).
With the last commit [b9acdf4] it shold be pretty close to functional.

If you feel like testing it, use it and let us know any issue or suggestion of any kind.

Thank you very much for your help!

I close this issue (at least for the moment), if it happens again we'll reopen it :)

**Comment by primetoxinz** [comment] 2017-05-16 18:47
yeah, appears it has something to do with a Credential Name including any character with a space on both sides, for example `hello - world`, when trying to read it back it crashes
In fact, even `<space>a` crashes.

**Comment by oyzzo** [comment] 2017-05-16 18:55
I can't reproduce the crash...
I'm using a credential with a name of "hello - world ⌚ " and it writes and reads without a problem.
Does it work for you?

**Comment by primetoxinz** [comment] 2017-05-16 18:57
Copy Pasting that exact string, writing works fine but reading back crashes.

**Comment by oyzzo** [comment] 2017-05-16 19:03
Ok I'll take a look into it, see how it can be rewritten in a more robust way and let you know so you can check it.

**Comment by oyzzo** [comment] 2017-05-25 06:10
I can confirm it also happens to me when compiling with QT5.5.

**Comment by oyzzo** [comment] 2017-08-09 20:23
It's been fixed in version 1.0.1

Also binaries for linux x32 and x64 have been provided:
https://github.com/oyzzo/MemTypeTool/releases

**Closed as completed by oyzzo** 2017-08-09 20:23 UTC
Labels: bug
